---
ssl_certs_country: "US"
ssl_certs_locality: "Charlotte"
ssl_certs_organization: "Your company"
ssl_certs_state: "NC"
ssl_certs_common_name: "{{inventory_hostname}}"
ssl_certs_days: "365"
ssl_certs_fields: "/C={{ssl_certs_country}}/ST={{ssl_certs_state}}/L={{ssl_certs_locality}}/O={{ssl_certs_organization}}/CN={{ssl_certs_common_name}}"


state_l: "latest"
apache: "httpd"
html_src: "/home/ansible/playbook/roles/webserver/files/index.html"
html_dest: "/var/www/html/index.html"
pri_owner: "root"
ssl: "mod_ssl"
ssl_dir: "/etc/ssl/private"
state_d: "directory"
newkey: "rsa:2048"
days: "365"
dh_out: "/etc/ssl/certs/dhparam.pem"
ssl_reg: "ssl_updated"
non_ssl_reg: "non_ssl_updated"
state_r: "restarted"
dh_sz: "2048"
backup: "yes"

include: ../files/awscrd.yml

html_path: /var/www/html
ssl_cert_file: /etc/ssl/certs/apache.crt
ssl_cert_key: /etc/ssl/private/apache.key

ssl_file: ssl.conf
non_ssl: non-ssl.conf
ssl_path: /etc/httpd/conf.d











